---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r, echo = FALSE, warning=FALSE, message = FALSE}
application <- "brazil"
source("data_functions.R")
source(paste0(application, "_data.R"))
source("plotting_functions.R")

```


```{r, echo = FALSE}
vSelectTime <- sort(d$idtime)[length(d$idtime)] # time for map
inputSelectVble <- "casos_est" # variable for map

# In Command Prompt for %G in (11, 12) do sed "27i inputSelectLoc2 <- %G"  C:\dengue-tracker\dengue-report-base.Rmd >  C:\dengue-tracker\dengue-report-%G.Rmd
# unique(map$idloc2) # All states
# inputSelectLoc2 <- map$idloc2[1] # state for map and time plot dput(unique(map$idloc2))

inputSelectLoc2 <- 41
```

# `r unique(map$nameloc2[which(map$idloc2 == inputSelectLoc2)])`

```{r, echo = FALSE}
mapF <- fnMapFiltered(vSelectTime, inputSelectLoc2, inputSelectVble)
dF <- fnDFiltered(inputSelectVble, mapF) # Select vble and locations in mapF (in state)
```

<!---
### Dengue and Google trends in each state (now cases each municipality)

 # ```{r, echo = FALSE}
# fnTimeplot(dF)
# ```
-->

### Corrected number of dengue cases via Google Trends

```{r trends-plot, fig.width=9, fig.height=4, fig.align = 'left', echo = FALSE}
state <- state_code |>
  filter(state_n == inputSelectLoc2) |>
  select(short) |>
  as.character()

model_preds <- generate_data(brazil_ufs, gamma = 0.90)

data <- model_preds |> filter(uf==state)

plot_trends_data(data, state)
```

<style>
.html-widget {
    margin: auto;
}
</style>

```{r, fig.width=7, fig.height=9, fig.align='center'}
panel_plot_states(data, state)
```

---
title: "Dengue Report - `r state`"
---
